stages:
  - check
  - test
  - build

variables:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: "true"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - target/

# 1. CHECK
check:
  image: rust:1.96
  stage: check
  before_script:
    - export PATH="/usr/local/rustup/toolchains/1.96.0-x86_64-unknown-linux-gnu/bin:$PATH"
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings
    - cargo check

# 2. TEST
test:
  image: rust:1.96
  stage: test
  services:
    # This spins up the actual background Docker daemon
    - name: docker:24.0.7-dind
      alias: docker
  variables:
    # Route all Docker requests from the Rust container to the DinD service over the open port
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    # Dummy URL here so TestDb::new() parses safely, 
    # E2E tests will spin up their own containers via Testcontainers!
    DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:5432/postgres"
  before_script:
    - export PATH="/usr/local/rustup/toolchains/1.96.0-x86_64-unknown-linux-gnu/bin:$PATH"
    # Install the missing docker CLI binary so the Testcontainers crate can talk to the daemon
    - apt-get update && apt-get install -y docker.io
  script:
    # Run everything! Unit tests, integration tests, and your Testcontainers E2E tests.
    - cargo test --bin doodoo-logistics-rust

# 3. BUILD
build:
  image: rust:1.96
  stage: build
  script:
    - cargo build --release